[package]
name = "raiden-sqs-derive"
version = "0.0.0"
authors = ["Yuki Kodama <endflow.net@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-quote = "0.3.2"
proc-macro2 = "^1"
quote = "^1"
syn = "^1.0.109"
